In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
print(np.arange(1,10,4))

[1 5 9]


In [ ]:
arr = np.array([1,4,5,8])
print(arr.reshape(2,2))

[[1 4]
 [5 8]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
a= np.eye(4, k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.array([1,2,2,3,2])
print(np.sum(arr))

10


In [ ]:
arr = np.array([10,20,30])
print(np.mean(arr))

20.0


In [ ]:
a = np.array([2,5,9,13])
print(np.max(a))

13


In [ ]:
arr = np.array([2,6,3,8,1])
print(np.min(arr))

1


In [ ]:
print(np.sqrt(7))

2.6457513110645907


In [ ]:
arr = np.array([1,7,8,2,6])
print(np.sort(arr))

[1 2 6 7 8]


In [ ]:
x = np.array([1,4,7])
y = np.array([1,6,2])
print(np.concatenate((x,y)))

[1 4 7 1 6 2]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr.size)


5


In [ ]:
arr = np.array([1,2,3,4])
print(np.append(arr,5))

[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4])
print(np.delete(arr,3))

[1 2 3]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))

[5 7 9]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.subtract(a,b))

[-3 -3 -3]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.multiply(a,b))

[ 4 10 18]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.log(3))

1.0986122886681098


In [ ]:
arr = np.array([10,20,30])
print(np.median(arr))

20.0


In [ ]:
arr = np.array([5,2,8,1,9])
print(np.sort(arr)[::-1])

[9 8 5 2 1]


In [ ]:
a=np.eye(3)
print(a)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
a=np.eye(3)
print(a)
+

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [ ]:
a=np.random.randint(1,10,5)
print(a)

[9 7 1 8 5]


In [ ]:
a=np.random.randint(1,10,5)
print(a)

[2 3 3 3 1]


In [ ]:
a=np.random.rand(5)
print(a)


[0.58485803 0.84899113 0.53131736 0.06622857 0.21580307]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)


2


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)


(2, 3)


In [ ]:
a=np.datetime64('2025-05-15')
print(a)

2025-05-15


In [ ]:
a=np.resize([1,2,3,4,5,6],(2,4))
print(a)

[[1 2 3 4]
 [5 6 1 2]]


In [ ]:
a=np.insert([1,2,3],1,10)
print(a)

[ 1 10  2  3]


In [ ]:
a=np.split([1,2,3,4,5,6],3)
print(a)

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
a=np.vstack(([1,2],[3,4]))
print(a)

[[1 2]
 [3 4]]


In [ ]:
a=np.hstack(([1,2],[3,4]))
print(a)

[1 2 3 4]


In [ ]:
a=np.array([10,20,30,40])
print(a[a>20])

[30 40]


In [ ]:
a=np.unique([1,2,2,3,3,4])
print(a)

[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([10,30,20,70])
print(arr[[0,2,3]])

[10 20 70]


In [ ]:
a = np.array([1,4,5])
b = a.copy()
print(b)

[1 4 5]


In [ ]:
a="HELLO ALL"
print(a.lower())

hello all


In [ ]:
a="hello"
print(a.upper())

HELLO


In [ ]:
a="Good morning to all"
print(a.split())

['Good', 'morning', 'to', 'all']


In [ ]:
a=['Hello','All']
print(" ".join(a))

Hello All


In [ ]:
a="Good morning all"
print(a.replace("morning","evening"))

Good evening all
