In [ ]:
import numpy as np

# creating two lists

a = [10,20,30]
b = [40,50,60]
arr = np.array([a,b])
print("Array:", arr)

# change to matrix
matrix = np.matrix(arr)
print("\n Matrix:", matrix)

# finding row wise mean
row_mean = np.mean(matrix,axis = 1)
print("\n Row wise mean")
print(row_mean)

# finding column wise np.average
column_average = np.var(matrix, axis = 0)
print("\n Column wise variance")
print(column_average)


Array: [[10 20 30]
 [40 50 60]]

 Matrix: [[10 20 30]
 [40 50 60]]

 Row wise mean
[[20.]
 [50.]]

 Column wise mean
[[225. 225. 225.]]
